# To add kernel into jupyter notebook
### create virtual env
### --> conda create --name condaenv
### --> conda activate condaenv # activate virtual env

## add this virtual environment as a kernel in jupyter notebook

### --> ipython kernal install --name = condaenv --user


In [5]:
# !jupyter kernelspec list --json
# conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

In [1]:
import torch
import numpy as np

In [13]:
print(torch.cuda.is_available())

False


In [38]:
# creating tensors with shape 5X2
x = torch.rand(4,4)
x

tensor([[0.6711, 0.3141, 0.3645, 0.5041],
        [0.0636, 0.3174, 0.4855, 0.8979],
        [0.3530, 0.3666, 0.8480, 0.8253],
        [0.9544, 0.6795, 0.7971, 0.2524]])

In [39]:
x[0,1].item() # getting the item or single tensor value

0.31407278776168823

In [40]:
a = x.view(-1,4) # converted into
a

tensor([[0.6711, 0.3141, 0.3645, 0.5041],
        [0.0636, 0.3174, 0.4855, 0.8979],
        [0.3530, 0.3666, 0.8480, 0.8253],
        [0.9544, 0.6795, 0.7971, 0.2524]])

In [41]:
x.size()

torch.Size([4, 4])

In [42]:
del x

## AutoGrad

In [21]:
x = torch.rand(5, requires_grad=True) # this states that we will need the gradients of these tensors
print(x)

tensor([0.2925, 0.8788, 0.0176, 0.3249, 0.1099], requires_grad=True)


In [22]:
y = x+2
y

tensor([2.2925, 2.8788, 2.0176, 2.3249, 2.1099], grad_fn=<AddBackward0>)

In [23]:
z = y*y*2
z = z.mean()
z

tensor(10.9884, grad_fn=<MeanBackward0>)

In [24]:
z.backward()
print(x.grad) # dz/dx # chain rule of jacobian product

tensor([1.8340, 2.3031, 1.6141, 1.8599, 1.6879])


In [30]:
del x

x = torch.rand(3, requires_grad=True)
x

tensor([0.8288, 0.6132, 0.3904], requires_grad=True)

In [31]:
y = x + 2
y

tensor([2.8288, 2.6132, 2.3904], grad_fn=<AddBackward0>)

## 3 ways to make tensors not consider the gradient
## This function will track the history of computation graph

#### 1. x.requires_grad_(False)
#### 2. x.detach()
#### 3. with torch.no_grad()

In [29]:
# 1
x.requires_grad_(False) # whenever we have trailing underscore, it torch will use inplace operation
x

tensor([0.5713, 0.6127, 0.9140])

In [32]:
# 2
y = x.detach()
y

tensor([0.8288, 0.6132, 0.3904])

In [33]:
# 3
with torch.no_grad():
    z = x+2
    print(z)

tensor([2.8288, 2.6132, 2.3904])


In [34]:
del z
del y
del x

# Back Propagation
## 3 Steps:
### 1. Forward Pass
### 2. Compute local gradients
### 3. Backward Pass: Compute dLoss/dWeights using chain rule

In [36]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True) # we need gradients of weights

# forward pass & compute the loss
y_hat = w*x
loss = (y_hat - y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [37]:
# backward pass, chain rule computations will be handled by pytorch
loss.backward()
print(w.grad)

tensor(-2.)
