# To add kernel into jupyter notebook
### create virtual env
### --> conda create --name condaenv
### --> conda activate condaenv # activate virtual env

## add this virtual environment as a kernel in jupyter notebook

### --> ipython kernal install --name = condaenv --user


In [5]:
# !jupyter kernelspec list --json
# conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

In [1]:
import torch
import numpy as np

In [2]:
print(torch.cuda.is_available())

True


In [3]:
# creating tensors with shape 5X2
x = torch.rand(4,4)
x

tensor([[0.7725, 0.4839, 0.1514, 0.7692],
        [0.5027, 0.4641, 0.2058, 0.1789],
        [0.7311, 0.3349, 0.5977, 0.4028],
        [0.8362, 0.5631, 0.6192, 0.1497]])

In [4]:
x[0,1].item() # getting the item or single tensor value

0.48388808965682983

In [5]:
a = x.view(-1,4) # converted into
a

tensor([[0.7725, 0.4839, 0.1514, 0.7692],
        [0.5027, 0.4641, 0.2058, 0.1789],
        [0.7311, 0.3349, 0.5977, 0.4028],
        [0.8362, 0.5631, 0.6192, 0.1497]])

In [6]:
x.size()

torch.Size([4, 4])

In [7]:
del x

## AutoGrad

In [8]:
x = torch.rand(5, requires_grad=True) # this states that we will need the gradients of these tensors
print(x)

tensor([0.0365, 0.7033, 0.1784, 0.1161, 0.0298], requires_grad=True)


In [9]:
y = x+2
y

tensor([2.0365, 2.7033, 2.1784, 2.1161, 2.0298], grad_fn=<AddBackward0>)

In [10]:
z = y*y*2
z = z.mean()
z

tensor(9.9195, grad_fn=<MeanBackward0>)

In [11]:
z.backward()
print(x.grad) # dz/dx # chain rule of jacobian product

tensor([1.6292, 2.1626, 1.7427, 1.6929, 1.6239])


In [12]:
del x

x = torch.rand(3, requires_grad=True)
x

tensor([0.9660, 0.8534, 0.7706], requires_grad=True)

In [13]:
y = x + 2
y

tensor([2.9660, 2.8534, 2.7706], grad_fn=<AddBackward0>)

## 3 ways to make tensors not consider the gradient
## This function will track the history of computation graph

#### 1. x.requires_grad_(False)
#### 2. x.detach()
#### 3. with torch.no_grad()

In [14]:
# 1
x.requires_grad_(False) # whenever we have trailing underscore, it torch will use inplace operation
x

tensor([0.9660, 0.8534, 0.7706])

In [15]:
# 2
y = x.detach()
y

tensor([0.9660, 0.8534, 0.7706])

In [16]:
# 3
with torch.no_grad():
    z = x+2
    print(z)

tensor([2.9660, 2.8534, 2.7706])


In [17]:
del z
del y
del x

# Back Propagation
## 3 Steps:
### 1. Forward Pass
### 2. Compute local gradients
### 3. Backward Pass: Compute dLoss/dWeights using chain rule

In [18]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True) # we need gradients of weights

# forward pass & compute the loss
y_hat = w*x
loss = (y_hat - y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [19]:
# backward pass, chain rule computations will be handled by pytorch
loss.backward()
print(w.grad)

tensor(-2.)
